Module lecical_elements

pragma_ ::= pragma identifier_ [(pragma_argument_association {, pragma_argument_association})];

pragma_argument_association ::=
                            [pragma_argument__identifier =>] name_
                            | [pragma_argument__identifier =>] expression_
                            | pragma_argument__aspect_mark => name_
                            | pragma_argument__aspect_mark => expression_

basic_declaration ::=
                  type_declaration
                  | object_declaration
                  | subprogram_declaration
                  | null_procedure_declaration
                  | package_declaration
                  | exception_declaration
                  | generic_instantiation
                  | subtype_declaration
                  | number_declaration
                  | abstract_subprogram_declaration
                  | expression_function_declaration
                  | renaming_declaration
                  | generic_declaration

defining_identifier ::= identifier_