Module example

aspect_clause ::= attribute_definition_clause
| enumeration_representation_clause
| record_representation_clause
| at_clause;
simple_return_statement ::= return [expression_];
simple_return_statement ::= return | return expression_;

pragma_ ::= pragma identifier [(pragma_argument_association {, pragma_argument_association})];

pragma_argument_association ::=
                            [pragma_argument__identifier =>] name_
                            | [pragma_argument__identifier =>] expression_
                            | pragma_argument__aspect_mark => name_
                            | pragma_argument__aspect_mark => expression_;
