aspect_clause ::= attribute_definition_clause
| enumeration_representation_clause
| record_representation_clause
| at_clause;
simple_return_statement ::= *return* [expression_];
simple_return_statement ::= *return* | *return* expression_;